# ---------------- #
#   Main Configs   #
# ---------------- #
url: "http://www.kuture.com.cn"
date_format: "ordinal"
title: "Kuture"
subtitle: "汲众言者博识,阅众家者博学"
description: "Kuture的个人博客"
keywords: Kuture, AI, Pytorch, Keras, Tensorflow, Pytorch, Python, Spider, austinkuture, iOS, Objective-C, Swift
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
leancloud:
  enable: true
  app_id: OuqtgYuaTMxmXSBx310IKuWY-gzGzoHsz
  app_key: AAiznz9nMSOA8uJqrJ9Cay6v

# ---------------- #
#      Author      #
# ---------------- #
author: Kuture
# organization: kuture.com.cn
# organization_url: http://www.kuture.com.cn
github_username: AustinKuture
location: BeiJing, China
email: austinkuture@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 百科

  #-#
    #href: /links/#
    #label: 链接#

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
# subscribe_rss: /feed.xml #

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
#kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: AustinKuture/austinkuture.github.io


# ---------------- #
#      Comments    #
# ---------------- #
#support provider: disqus, gitment, gitalk
#comment:
  #gitment:AustinKuture


# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
    #analytics_id: UA-80669434-1
